import type { RuntimeScenario } from '../types';
import { stage } from './helpers';

// 渠道侧故障 + 恢复回弹场景：单一银行渠道故障（商户与平台都无过错），
// 恢复判断第一轮遇到回弹判「未稳定」，带新观测窗口重入后才闭环——验证恢复判据的抗回弹能力。
// verify 关键：channel_breakdown 显示异常集中在工行渠道，其他渠道正常。
export const channelReboundScenario: RuntimeScenario = {
  id: 'channel-rebound',
  label: '渠道回弹 P0',
  summary: '银行渠道故障引发成功率骤降，恢复期回弹被识破，二次判断才闭环。',
  incidentId: 'INC-20260825-024',
  expectedPath: ['verify', 'locate', 'contact', 'escalate', 'recover', 'recover', 'evaluate'],
  groundTruth: {
    isIncident: true,
    severity: 'P0',
    rootCause: '工行渠道支付网关故障',
    acceptableCauses: ['银行渠道故障', '渠道网关异常', '工行渠道异常'],
    rootCauseKeywords: ['渠道', '工行'],
    recovered: true,
  },
  incident: {
    merchant: '万象零售',
    severity: 'P0',
    impact: '¥152.7万',
    title: '银行渠道成功率骤降',
    detectedAt: '2026-08-26 13:46:05',
  },
  stages: {
    verify: stage({
      stage: 'verify',
      title: '智能核验结果',
      goal: '多源信号聚合判断：异常集中在单一银行渠道，其他渠道正常 → 渠道侧故障。',
      context: { incidentId: 'INC-20260825-024', window: '13:42–13:50' },
      tools: [
        {
          name: 'metrics.query',
          displayName: 'Metrics Query',
          category: 'metrics',
          input: { window: '13:42–13:50', granularity: '1m', metrics: ['pay.success_rate', 'merchant.p95_rt', 'pay.success_rate.by_channel'] },
          output: {
            successRate: [{ t: '13:42', v: 99.7 }, { t: '13:46', v: 62.18 }, { t: '13:50', v: 64.2 }],
            p95Rt: [{ t: '13:42', v: 134 }, { t: '13:46', v: 8240 }, { t: '13:50', v: 7920 }],
            byChannel: {
              icbc: { successRate: 0.124, p95Rt: 8240 },
              alipay: { successRate: 0.995, p95Rt: 132 },
              wechat: { successRate: 0.996, p95Rt: 128 },
            },
          },
          latencyMs: 528, status: 'success', flagged: true,
          flagReason: '整体 -37.52pp，工行渠道 12.4% 是拖累主因',
          chartHint: 'channel_breakdown',
        },
        {
          name: 'alerts.context_fetch',
          displayName: 'Alert Context',
          category: 'alert',
          input: { incidentId: 'INC-20260825-024', window: '20m' },
          output: {
            alerts: [
              { id: 'ALT-1342', severity: 'P0', rule: 'channel_success_rate<50%', firedAt: '13:42:18' },
              { id: 'ALT-1344', severity: 'P0', rule: 'channel_error_rate>40%', firedAt: '13:44:02' },
            ],
            correlatedCount: 2,
            alertCategory: '渠道级故障（仅工行）',
          },
          latencyMs: 302, status: 'success', flagged: true,
          flagReason: '渠道类告警集中指向工行',
        },
        {
          name: 'logs.search',
          displayName: 'Logs Search',
          category: 'log',
          input: { service: 'channel-router', keyword: 'icbc OR GATEWAY_ERROR', window: '13:42–13:50' },
          output: {
            total: 14286,
            sample: [
              '13:46:05 ERROR icbc gateway timeout (channel=icbc, error=GATEWAY_ERROR, ratio=87.6%)',
              '13:46:08 ERROR icbc gateway timeout (channel=icbc, error=GATEWAY_ERROR, ratio=89.1%)',
            ],
            topError: 'GATEWAY_ERROR',
          },
          latencyMs: 1024, status: 'success', flagged: true,
          flagReason: 'icbc gateway timeout 集中爆发（87.6% 错误率）',
          chartHint: 'log_excerpt',
        },
        {
          name: 'change_records.list',
          displayName: 'Change Records',
          category: 'change',
          input: { services: ['channel-router', 'merchant-cashier'], window: '24h' },
          output: { changes: [], note: '商户与平台侧均无相关变更' },
          latencyMs: 356, status: 'success', flagged: false,
          flagReason: '商户与平台侧均无变更 → 排除内部诱因',
          chartHint: 'change_timeline',
        },
      ],
      decision: '3 源工具异常 + 1 源未 flag：Metrics 异常集中在工行渠道、Alerts 渠道级、Logs 渠道网关错误。综合判定：真实 P0 故障，根因归属渠道侧。',
      decisionFactors: [
        { label: '成功率跌幅', value: '-37.52pp', evidence: 'metrics://pay.success_rate' },
        { label: '渠道集中度', value: '异常全部来自工行渠道', evidence: 'metrics://pay.success_rate/by-channel' },
        { label: '其余渠道', value: '99.5%（正常）', evidence: 'metrics://pay.success_rate/others' },
      ],
      output: {
        isIncident: true,
        severity: 'P0',
        affectedScope: '万象零售工行渠道支付',
        evidenceGrounded: true,
        signalSummary: '3/4 工具异常（Metrics/Alerts/Logs 全部指向工行渠道）',
      },
      metrics: { latencyMs: 1280, inputTokens: 624, outputTokens: 226, costYuan: 0.06, confidence: 96, toolCalls: 4, evidenceCount: 4 },
      gate: '真实故障且置信度 ≥ 90%',
      successMetric: 'P0 Recall ≥ 99%',
      risk: '渠道级抖动可能被放大为全局故障。',
      fallback: '置信度不足时转人工核验，不自动升级。',
    }),
    locate: stage({
      stage: 'locate',
      title: '根因定位结果',
      goal: '关联指标、日志、变更与历史案例，输出可审计根因并判定归属。',
      context: { incident: 'P0', service: 'channel-router', window: '13:42–13:50', channelSplit: '工行 12.4% / 其余 99.5%' },
      tools: [
        {
          name: 'channel.health',
          displayName: 'Channel Health',
          category: 'channel',
          input: { channel: 'icbc', window: '20m' },
          output: { gatewayErrorRatio: 0.876, p95Rt: 8240, upstreamAckMs: 0, healthStatus: 'down' },
          latencyMs: 486, status: 'success', flagged: true,
          flagReason: '工行渠道网关返回 GATEWAY_ERROR 比例 87.6%',
          chartHint: 'metric_trend',
        },
        {
          name: 'logs.search',
          displayName: 'Logs Search（深查）',
          category: 'log',
          input: { service: 'channel-router', keyword: 'icbc', window: '13:42–13:50' },
          output: { total: 14286, sample: ['13:46:05 ERROR icbc gateway timeout (channel=icbc, error=GATEWAY_ERROR)'] },
          latencyMs: 1024, status: 'success', flagged: true,
          flagReason: '工行渠道请求超时与错误码激增',
          chartHint: 'log_excerpt',
        },
        {
          name: 'change_records.list',
          displayName: 'Change Records（深查）',
          category: 'change',
          input: { services: ['channel-router', 'merchant-cashier'], window: '72h' },
          output: { changes: [], note: '商户与平台侧 72h 内均无变更' },
          latencyMs: 356, status: 'success', flagged: false,
          flagReason: '排除内部诱因',
          chartHint: 'change_timeline',
        },
        {
          name: 'case_rag.retrieve',
          displayName: 'Case RAG',
          category: 'case',
          input: { query: '工行渠道网关故障 GATEWAY_ERROR', topK: 3 },
          output: { cases: [{ id: 'CASE-20260512-009', title: '工行渠道网关故障 45 分钟修复', similarity: 0.938, resolved: '渠道方修复并切流回原渠道' }] },
          latencyMs: 1342, status: 'success', flagged: true,
          flagReason: '召回 2026-05-12 工行渠道同型故障，相似度 93.8%',
          chartHint: 'case_similarity',
        },
      ],
      decision: 'Top-1 根因为工行渠道支付网关故障，归属渠道侧。',
      decisionFactors: [
        { label: '渠道错误率', value: 'GATEWAY_ERROR 87.6%', evidence: 'channel://icbc/gateway-error' },
        { label: '商户/平台变更', value: '均无', evidence: 'change://none' },
        { label: '案例相似度', value: '93.8%', evidence: 'case://2026-05-12-009' },
      ],
      output: {
        topCause: '工行渠道支付网关故障',
        alternatives: ['渠道路由配置异常', '银行侧限流'],
        causeOwner: 'channel',
        recommendedAction: '临时切流至备用渠道，并向渠道方通报',
      },
      metrics: { latencyMs: 3980, inputTokens: 1406, outputTokens: 458, costYuan: 0.17, confidence: 92, toolCalls: 4, evidenceCount: 4 },
      gate: 'Top-1 置信度 ≥ 85%，根因归属明确',
      successMetric: 'Root Cause Top-1 Accuracy ≥ 85%，归属判定准确率',
      risk: '渠道方故障修复时间不受平台控制。',
      fallback: '归属存疑时保留切流预案并请渠道运营确认。',
    }),
    contact: stage({
      stage: 'contact',
      title: '商户触达方案',
      goal: '故障不在商户侧：以安抚与替代方案为主，避免商户自查浪费时间。',
      context: { merchantTier: '战略商户', channel: '站内信 + 短信', confirmedCause: '工行渠道网关故障', tone: 'reassurance' },
      tools: [
        {
          name: 'merchant.profile',
          displayName: 'Merchant Profile',
          category: 'merchant',
          input: { merchantId: 'm-wanxiang', fields: ['tier', 'contacts', 'channel_preference'] },
          output: { tier: '战略商户', contacts: [{ name: '陈总', role: '运营总监' }], channelPreference: ['站内信', '短信'] },
          latencyMs: 278, status: 'success', flagged: false,
        },
        {
          name: 'message.composer',
          displayName: 'Message Composer',
          category: 'message',
          input: { facts: ['工行渠道网关故障', '与商户系统无关', '已临时切流至备用渠道', '建议收银台引导用户优先使用其他支付方式'], tone: 'reassurance' },
          output: {
            subject: '工行渠道支付异常处置通知',
            message: '检测到工行渠道支付网关故障，与贵司系统无关，无需排查自身服务。我们已临时将流量切换至备用渠道，建议收银台引导用户优先使用其他支付方式，恢复进展将持续同步。',
            actionLinkLabel: '查看渠道恢复进展',
          },
          latencyMs: 512, status: 'success', flagged: false,
          flagReason: '明确说明故障不在商户侧，避免商户误自查',
        },
      ],
      decision: '安抚类内容已生成，等待人工批准后发送。',
      decisionFactors: [
        { label: '触达类型', value: '安抚 + 替代方案（渠道侧故障）', evidence: 'trace://locate/causeOwner' },
        { label: '事实边界', value: '明确故障不在商户侧', evidence: 'trace://locate/output' },
      ],
      output: {
        subject: '工行渠道支付异常处置通知',
        message: '检测到工行渠道支付网关故障，与贵司系统无关，无需排查自身服务。我们已临时将流量切换至备用渠道，建议收银台引导用户优先使用其他支付方式，恢复进展将持续同步。',
        tone: 'reassurance',
        actionLinkLabel: '查看渠道恢复进展',
      },
      metrics: { latencyMs: 1010, inputTokens: 462, outputTokens: 172, costYuan: 0.05, confidence: 95, toolCalls: 2, evidenceCount: 2 },
      gate: '高影响外部动作必须人工批准',
      successMetric: '送达率、点击率与商户满意度',
      risk: '渠道恢复时间不确定，承诺过度会失信。',
      fallback: '拒绝后转人工电话沟通并记录原因。',
      requiresApproval: true,
    }),
    escalate: stage({
      stage: 'escalate',
      title: '故障升级结果',
      goal: '依据影响面和持续时间匹配升级策略与责任团队。',
      context: { severity: 'P0', impact: '¥152.7万', duration: '14m 55s', causeOwner: 'channel', recoveryProgress: '已切流备用渠道' },
      tools: [
        {
          name: 'policy.engine',
          displayName: 'Policy Engine',
          category: 'policy',
          input: { severity: 'P0', causeOwner: 'channel', impact: '¥152.7万' },
          output: { matched: 'P0 渠道侧故障 → 双团队联合升级', sla: '10 分钟' },
          latencyMs: 172, status: 'success', flagged: false,
          flagReason: '命中 P0 渠道侧故障升级策略',
        },
        {
          name: 'oncall.directory',
          displayName: 'On-call Directory',
          category: 'oncall',
          input: { teams: ['channel-ops', 'payment-router'] },
          output: { oncall: [{ team: '渠道运营', primary: '吴*' }, { team: '支付路由', primary: '孙*' }] },
          latencyMs: 138, status: 'success', flagged: false,
        },
        {
          name: 'ticket.create',
          displayName: 'Ticket',
          category: 'ticket',
          input: { severity: 'P0', title: 'MOCK-INC-024 工行渠道网关故障', teams: ['渠道运营', '支付路由'] },
          output: { ticketId: 'MOCK-INC-024', simulated: true },
          latencyMs: 150, status: 'success', flagged: false,
        },
      ],
      decision: '升级至渠道运营 + 支付路由联合处置，SLA 10 分钟。',
      decisionFactors: [
        { label: '事故等级', value: 'P0', evidence: 'trace://verify/severity' },
        { label: '根因归属', value: '渠道侧', evidence: 'trace://locate/causeOwner' },
      ],
      output: { ticketId: 'MOCK-INC-024', teams: ['渠道运营', '支付路由'], sla: '10 分钟', escalationLevel: 'P0 联合处置', simulated: true },
      metrics: { latencyMs: 470, inputTokens: 188, outputTokens: 104, costYuan: 0.03, confidence: 97, toolCalls: 3, evidenceCount: 2 },
      gate: 'P0 或影响金额 ≥ ¥100万',
      successMetric: '升级策略命中率与 SLA 达成率',
      risk: '渠道方响应时效不受平台 SLA 约束。',
      fallback: '渠道方超时未响应则提升通报级别。',
    }),
    recover: stage({
      stage: 'recover',
      title: '恢复判断结果',
      goal: '用连续观测窗口确认真实恢复，防止指标短暂回弹。',
      context: { windows: ['14:02–14:04', '14:04–14:06', '14:06–14:08'], baseline: '近 7 日同小时', channelStatus: '渠道方通报修复中' },
      tools: [
        {
          name: 'metrics.query',
          displayName: 'Metrics Query',
          category: 'metrics',
          input: { window: '14:02–14:08', granularity: '1m', metrics: ['pay.success_rate', 'channel.health.icbc'] },
          output: {
            successRate: [{ t: '14:02', v: 99.2 }, { t: '14:04', v: 81.4 }, { t: '14:06', v: 88.2 }, { t: '14:08', v: 92.6 }],
            channelHealthIcbc: [{ t: '14:02', v: 0.96 }, { t: '14:04', v: 0.78 }, { t: '14:06', v: 0.85 }, { t: '14:08', v: 0.93 }],
          },
          latencyMs: 1068, status: 'success', flagged: true,
          flagReason: '第 2 窗口回弹至 81.4%，第 1 窗口 99.2% 不可持续',
          chartHint: 'metric_trend',
        },
        {
          name: 'channel.health',
          displayName: 'Channel Health',
          category: 'channel',
          input: { channel: 'icbc', window: '14:02–14:08' },
          output: { gatewayErrorRatio: [0.04, 0.18, 0.12, 0.07], healthStatus: 'flapping' },
          latencyMs: 442, status: 'success', flagged: true,
          flagReason: '工行渠道错误率仍在波动，未收敛',
          chartHint: 'metric_trend',
        },
      ],
      decision: '第 2 窗口出现回弹，不满足连续稳定，保持事故打开。',
      decisionFactors: [
        { label: '窗口 1 成功率', value: '99.2%', evidence: 'metrics://pay.success_rate/w1' },
        { label: '窗口 2 成功率', value: '81.4%（回弹）', evidence: 'metrics://pay.success_rate/w2' },
        { label: '稳定窗口', value: '1/3', evidence: 'metrics://recovery/windows' },
      ],
      output: { recovered: false, stableWindows: 1, residualRisk: '高', observationAdvice: '渠道方修复未收敛，等待下一批观测窗口' },
      metrics: { latencyMs: 1720, inputTokens: 534, outputTokens: 186, costYuan: 0.09, confidence: 93, toolCalls: 2, evidenceCount: 3 },
      gate: '连续三个窗口均回到基线范围',
      successMetric: '恢复误判率与 MTTR',
      risk: '把回弹当恢复会造成二次故障通报，伤害商户信任。',
      fallback: '任一窗口不达标则保持事故打开，等待新窗口重判。',
    }),
    evaluate: stage({
      stage: 'evaluate',
      title: '评测回流结果',
      goal: '把最终处置事实沉淀为可复用评测样本。',
      context: { labelSource: '渠道方通报 + 二次恢复窗口 + 人工审批', promptVersion: 'v3.4', recoveryAttempts: 2 },
      tools: [
        {
          name: 'eval.store',
          displayName: 'Eval Store',
          category: 'eval',
          input: { runId: 'RUN-024', tags: ['verify_tp', 'root_cause_top1', 'cause_owner_channel', 'rebound_detected'] },
          output: { stored: true, sampleId: 'EVAL-20260826-024' },
          latencyMs: 276, status: 'success', flagged: false,
        },
        {
          name: 'metric.calculator',
          displayName: 'Metric Calculator',
          category: 'metric',
          input: { period: 'today', metrics: ['recovery_false_positive_rate', 'mttr_minutes'] },
          output: { recoveryFalsePositiveRate: 0.04, mttrMinutes: 18.6 },
          latencyMs: 352, status: 'success', flagged: false,
        },
      ],
      decision: '样本通过质量检查，回弹识别案例入库。',
      decisionFactors: [
        { label: '核验结果', value: 'TP', evidence: 'eval://verify/024' },
        { label: 'Top-1 根因', value: '命中', evidence: 'eval://root-cause/024' },
        { label: '回弹识别', value: '第一轮正确拒绝闭环', evidence: 'eval://recovery/024' },
      ],
      output: { sampleId: 'EVAL-20260826-024', finalRootCause: '工行渠道支付网关故障', humanCorrected: false, dataset: 'merchant-incident-v12' },
      metrics: { latencyMs: 634, inputTokens: 318, outputTokens: 128, costYuan: 0.04, confidence: 98, toolCalls: 2, evidenceCount: 3 },
      gate: '最终事实、人工反馈和恢复结果齐全',
      successMetric: 'Recall、F1、恢复误判率与 MTTR',
      risk: '错误标签会放大后续评测偏差。',
      fallback: '证据不完整的样本进入待标注队列。',
    }),
  },
  retryStages: {
    // 恢复判断第 2 次：换新观测窗口（渠道方已完成修复），mock 与真实模式共用这份新输入。
    recover: [
      stage({
        stage: 'recover',
        title: '恢复判断结果（第 2 轮）',
        goal: '基于新一批观测窗口重新确认恢复，上一轮存在回弹。',
        context: { windows: ['14:10–14:12', '14:12–14:14', '14:14–14:16'], baseline: '近 7 日同小时', channelStatus: '渠道方 14:09 通报修复完成', attemptNote: '第 2 次恢复判断：上一轮第 2 窗口回弹至 81.4%' },
        tools: [
          {
            name: 'metrics.query',
            displayName: 'Metrics Query',
            category: 'metrics',
            input: { window: '14:10–14:16', granularity: '1m', metrics: ['pay.success_rate', 'channel.health.icbc'] },
            output: {
              successRate: [{ t: '14:10', v: 99.4 }, { t: '14:12', v: 99.6 }, { t: '14:14', v: 99.5 }, { t: '14:16', v: 99.7 }],
              channelHealthIcbc: [{ t: '14:10', v: 0.995 }, { t: '14:12', v: 0.998 }, { t: '14:14', v: 0.996 }, { t: '14:16', v: 0.998 }],
            },
            latencyMs: 1102, status: 'success', flagged: false,
            flagReason: '三个新窗口成功率 99.4% / 99.6% / 99.5%，工行渠道回到基线',
            chartHint: 'metric_trend',
          },
          {
            name: 'channel.health',
            displayName: 'Channel Health',
            category: 'channel',
            input: { channel: 'icbc', window: '14:10–14:16' },
            output: { gatewayErrorRatio: [0.005, 0.002, 0.004, 0.002], healthStatus: 'healthy' },
            latencyMs: 428, status: 'success', flagged: false,
            flagReason: '工行渠道错误率回到基线',
            chartHint: 'metric_trend',
          },
        ],
        decision: '连续三个窗口稳定且渠道方确认修复，事故可以关闭。',
        decisionFactors: [
          { label: '支付成功率', value: '99.5%（三窗口均值）', evidence: 'metrics://pay.success_rate/recovery-2' },
          { label: '渠道方通报', value: '14:09 修复完成', evidence: 'channel://icbc/notice' },
          { label: '稳定窗口', value: '3/3', evidence: 'metrics://recovery/windows-2' },
        ],
        output: { recovered: true, stableWindows: 3, residualRisk: '低', observationAdvice: '切流回原渠道后继续观察 15 分钟' },
        metrics: { latencyMs: 1840, inputTokens: 586, outputTokens: 198, costYuan: 0.1, confidence: 95, toolCalls: 2, evidenceCount: 3 },
        gate: '连续三个窗口均回到基线范围',
        successMetric: '恢复误判率与 MTTR',
        risk: '渠道方修复后可能存在积压请求重放。',
        fallback: '任一窗口不达标则继续保持事故打开。',
      }),
    ],
  },
};