import type { RuntimeScenario } from '../types';
import { stage } from './helpers';

// 渠道侧故障 + 恢复回弹场景：单一银行渠道故障（商户与平台都无过错），
// 恢复判断第一轮遇到回弹判「未稳定」，带新观测窗口重入后才闭环——验证恢复判据的抗回弹能力。
export const channelReboundScenario: RuntimeScenario = {
  id: 'channel-rebound',
  label: '渠道回弹 P0',
  summary: '银行渠道故障引发成功率骤降，恢复期回弹被识破，二次判断才闭环。',
  incidentId: 'INC-20260825-024',
  monitorImage: '/mock/merchant-monitor-channel-rebound.png',
  expectedPath: ['verify', 'locate', 'contact', 'escalate', 'recover', 'recover', 'evaluate'],
  groundTruth: {
    isIncident: true,
    severity: 'P0',
    rootCause: '工行渠道支付网关故障',
    acceptableCauses: ['银行渠道故障', '渠道网关异常', '工行渠道异常'],
    rootCauseKeywords: ['渠道', '工行'],
    recovered: true,
  },
  incident: {
    merchant: '万象零售',
    severity: 'P0',
    impact: '¥152.7万',
    title: '银行渠道成功率骤降',
    detectedAt: '2026-08-26 13:46:05',
  },
  stages: {
    verify: stage({
      stage: 'verify',
      title: '智能核验结果',
      goal: '确认告警是否为真实故障，并识别影响等级。',
      input: {
        paymentSuccessRate: '99.70% → 62.18%',
        channelSuccessRate: '工行渠道 12.4% / 其余渠道 99.5%',
        p95Latency: '134ms → 8,240ms（仅工行渠道）',
        observationWindow: '连续 4 分钟',
      },
      tools: [
        ['Metrics', '按渠道拆分成功率，异常集中在单一渠道', 528],
        ['Alert Context', '合并渠道类告警并确认影响面', 302],
      ],
      decision: '真实 P0 故障：单一渠道故障拖垮整体成功率。',
      decisionFactors: [
        { label: '成功率跌幅', value: '-37.52pp', evidence: 'metric://pay.success_rate' },
        { label: '渠道集中度', value: '异常全部来自工行渠道', evidence: 'metric://pay.success_rate/by-channel' },
        { label: '其余渠道', value: '99.5%（正常）', evidence: 'metric://pay.success_rate/others' },
      ],
      output: {
        isIncident: true,
        severity: 'P0',
        affectedScope: '万象零售工行渠道支付',
        evidenceGrounded: true,
      },
      metrics: { latencyMs: 1280, inputTokens: 624, outputTokens: 226, costYuan: 0.06, confidence: 96, toolCalls: 2, evidenceCount: 3 },
      gate: '真实故障且置信度 ≥ 90%',
      successMetric: 'P0 Recall ≥ 99%',
      risk: '渠道级抖动可能被放大为全局故障。',
      fallback: '置信度不足时转人工核验，不自动升级。',
    }),
    locate: stage({
      stage: 'locate',
      title: '根因定位结果',
      goal: '关联指标、日志、变更与历史案例，输出可审计根因并判定归属。',
      input: { incident: 'P0', service: 'channel-router', window: '13:42–13:50', channelSplit: '工行 12.4% / 其余 99.5%' },
      tools: [
        ['Channel Health', '工行渠道网关返回 GATEWAY_ERROR 比例 87.6%', 486],
        ['Logs', '工行渠道请求超时与错误码激增', 1024],
        ['Change Records', '商户与平台侧均无相关变更', 356],
        ['Case RAG', '召回 2026-05-12 工行渠道同型故障', 1342],
      ],
      decision: 'Top-1 根因为工行渠道支付网关故障，归属渠道侧。',
      decisionFactors: [
        { label: '渠道错误率', value: 'GATEWAY_ERROR 87.6%', evidence: 'channel://icbc/gateway-error' },
        { label: '商户/平台变更', value: '均无', evidence: 'change://none' },
        { label: '案例相似度', value: '93.8%', evidence: 'case://2026-05-12-009' },
      ],
      output: {
        topCause: '工行渠道支付网关故障',
        alternatives: ['渠道路由配置异常', '银行侧限流'],
        causeOwner: 'channel',
        recommendedAction: '临时切流至备用渠道，并向渠道方通报',
      },
      metrics: { latencyMs: 3980, inputTokens: 1406, outputTokens: 458, costYuan: 0.17, confidence: 92, toolCalls: 4, evidenceCount: 4 },
      gate: 'Top-1 置信度 ≥ 85%，根因归属明确',
      successMetric: 'Root Cause Top-1 Accuracy ≥ 85%，归属判定准确率',
      risk: '渠道方故障修复时间不受平台控制。',
      fallback: '归属存疑时保留切流预案并请渠道运营确认。',
    }),
    contact: stage({
      stage: 'contact',
      title: '商户触达方案',
      goal: '故障不在商户侧：以安抚与替代方案为主，避免商户自查浪费时间。',
      input: { merchantTier: '战略商户', channel: '站内信 + 短信', confirmedCause: '工行渠道网关故障', tone: '安抚 + 替代方案' },
      tools: [
        ['Merchant Profile', '读取商户等级、联系人与渠道偏好', 278],
        ['Message Composer', '生成安抚类通知与替代支付建议', 512],
      ],
      decision: '安抚类内容已生成，等待人工批准后发送。',
      decisionFactors: [
        { label: '触达类型', value: '安抚 + 替代方案（渠道侧故障）', evidence: 'trace://locate/causeOwner' },
        { label: '事实边界', value: '明确故障不在商户侧', evidence: 'trace://locate/output' },
      ],
      output: {
        subject: '工行渠道支付异常处置通知',
        message: '检测到工行渠道支付网关故障，与贵司系统无关，无需排查自身服务。我们已临时将流量切换至备用渠道，建议收银台引导用户优先使用其他支付方式，恢复进展将持续同步。',
        tone: 'reassurance',
        actionLinkLabel: '查看渠道恢复进展',
      },
      metrics: { latencyMs: 1010, inputTokens: 462, outputTokens: 172, costYuan: 0.05, confidence: 95, toolCalls: 2, evidenceCount: 2 },
      gate: '高影响外部动作必须人工批准',
      successMetric: '送达率、点击率与商户满意度',
      risk: '渠道恢复时间不确定，承诺过度会失信。',
      fallback: '拒绝后转人工电话沟通并记录原因。',
      requiresApproval: true,
    }),
    escalate: stage({
      stage: 'escalate',
      title: '故障升级结果',
      goal: '依据影响面和持续时间匹配升级策略与责任团队。',
      input: { severity: 'P0', impact: '¥152.7万', duration: '14m 55s', causeOwner: 'channel', recoveryProgress: '已切流备用渠道' },
      tools: [
        ['Policy Engine', '命中 P0 渠道侧故障升级策略', 172],
        ['On-call Directory', '定位渠道运营与支付路由值班', 138],
        ['Ticket', '创建仿真工单 MOCK-INC-024', 150],
      ],
      decision: '升级至渠道运营 + 支付路由联合处置，SLA 10 分钟。',
      decisionFactors: [
        { label: '事故等级', value: 'P0', evidence: 'trace://verify/severity' },
        { label: '根因归属', value: '渠道侧', evidence: 'trace://locate/causeOwner' },
      ],
      output: { ticketId: 'MOCK-INC-024', teams: ['渠道运营', '支付路由'], sla: '10 分钟', escalationLevel: 'P0 联合处置', simulated: true },
      metrics: { latencyMs: 470, inputTokens: 188, outputTokens: 104, costYuan: 0.03, confidence: 97, toolCalls: 3, evidenceCount: 2 },
      gate: 'P0 或影响金额 ≥ ¥100万',
      successMetric: '升级策略命中率与 SLA 达成率',
      risk: '渠道方响应时效不受平台 SLA 约束。',
      fallback: '渠道方超时未响应则提升通报级别。',
    }),
    recover: stage({
      stage: 'recover',
      title: '恢复判断结果',
      goal: '用连续观测窗口确认真实恢复，防止指标短暂回弹。',
      input: { windows: ['14:02–14:04', '14:04–14:06', '14:06–14:08'], baseline: '近 7 日同小时', channelStatus: '渠道方通报修复中' },
      tools: [
        ['Metrics', '第 1 窗口回升至 99.2%，第 2 窗口回落至 81.4%', 1068],
        ['Channel Health', '工行渠道错误率仍在波动', 442],
      ],
      decision: '第 2 窗口出现回弹，不满足连续稳定，保持事故打开。',
      decisionFactors: [
        { label: '窗口 1 成功率', value: '99.2%', evidence: 'metric://pay.success_rate/w1' },
        { label: '窗口 2 成功率', value: '81.4%（回弹）', evidence: 'metric://pay.success_rate/w2' },
        { label: '稳定窗口', value: '1/3', evidence: 'metric://recovery/windows' },
      ],
      output: { recovered: false, stableWindows: 1, residualRisk: '高', observationAdvice: '渠道方修复未收敛，等待下一批观测窗口' },
      metrics: { latencyMs: 1720, inputTokens: 534, outputTokens: 186, costYuan: 0.09, confidence: 93, toolCalls: 2, evidenceCount: 3 },
      gate: '连续三个窗口均回到基线范围',
      successMetric: '恢复误判率与 MTTR',
      risk: '把回弹当恢复会造成二次故障通报，伤害商户信任。',
      fallback: '任一窗口不达标则保持事故打开，等待新窗口重判。',
    }),
    evaluate: stage({
      stage: 'evaluate',
      title: '评测回流结果',
      goal: '把最终处置事实沉淀为可复用评测样本。',
      input: { labelSource: '渠道方通报 + 二次恢复窗口 + 人工审批', promptVersion: 'v3.4', recoveryAttempts: 2 },
      tools: [
        ['Eval Store', '写入根因、归属与回弹识别标签', 276],
        ['Metric Calculator', '刷新恢复误判率与 MTTR 指标', 352],
      ],
      decision: '样本通过质量检查，回弹识别案例入库。',
      decisionFactors: [
        { label: '核验结果', value: 'TP', evidence: 'eval://verify/024' },
        { label: 'Top-1 根因', value: '命中', evidence: 'eval://root-cause/024' },
        { label: '回弹识别', value: '第一轮正确拒绝闭环', evidence: 'eval://recovery/024' },
      ],
      output: { sampleId: 'EVAL-20260826-024', finalRootCause: '工行渠道支付网关故障', humanCorrected: false, dataset: 'merchant-incident-v12' },
      metrics: { latencyMs: 634, inputTokens: 318, outputTokens: 128, costYuan: 0.04, confidence: 98, toolCalls: 2, evidenceCount: 3 },
      gate: '最终事实、人工反馈和恢复结果齐全',
      successMetric: 'Recall、F1、恢复误判率与 MTTR',
      risk: '错误标签会放大后续评测偏差。',
      fallback: '证据不完整的样本进入待标注队列。',
    }),
  },
  retryStages: {
    // 恢复判断第 2 次：换新观测窗口（渠道方已完成修复），mock 与真实模式共用这份新输入。
    recover: [
      stage({
        stage: 'recover',
        title: '恢复判断结果（第 2 轮）',
        goal: '基于新一批观测窗口重新确认恢复，上一轮存在回弹。',
        input: { windows: ['14:10–14:12', '14:12–14:14', '14:14–14:16'], baseline: '近 7 日同小时', channelStatus: '渠道方 14:09 通报修复完成', attemptNote: '第 2 次恢复判断：上一轮第 2 窗口回弹至 81.4%' },
        tools: [
          ['Metrics', '三个新窗口成功率 99.4% / 99.6% / 99.5%', 1102],
          ['Channel Health', '工行渠道错误率回到基线', 428],
        ],
        decision: '连续三个窗口稳定且渠道方确认修复，事故可以关闭。',
        decisionFactors: [
          { label: '支付成功率', value: '99.5%（三窗口均值）', evidence: 'metric://pay.success_rate/recovery-2' },
          { label: '渠道方通报', value: '14:09 修复完成', evidence: 'channel://icbc/notice' },
          { label: '稳定窗口', value: '3/3', evidence: 'metric://recovery/windows-2' },
        ],
        output: { recovered: true, stableWindows: 3, residualRisk: '低', observationAdvice: '切流回原渠道后继续观察 15 分钟' },
        metrics: { latencyMs: 1840, inputTokens: 586, outputTokens: 198, costYuan: 0.1, confidence: 95, toolCalls: 2, evidenceCount: 3 },
        gate: '连续三个窗口均回到基线范围',
        successMetric: '恢复误判率与 MTTR',
        risk: '渠道方修复后可能存在积压请求重放。',
        fallback: '任一窗口不达标则继续保持事故打开。',
      }),
    ],
  },
};
