import type { RuntimeScenario } from '../types';
import { stage } from './helpers';

// 误报收敛场景：大促流量触发容量类告警，核验判非故障后短路到评测回流（TN 样本）。
// verify 阶段关键：Metrics 显示流量大涨但成功率/延迟在基线内；Calendar 显示已登记大促；Alerts/Logs 均为容量类而非错误率类。
// 4 个工具中只有 Alerts 弱 flag，其他 3 个均不 flag → isIncident=false。
export const falseAlarmScenario: RuntimeScenario = {
  id: 'false-alarm',
  label: '大促误报 P2',
  summary: '大促流量上涨触发限流告警，核验识别为误报并短路回流负样本。',
  incidentId: 'INC-20260825-019',
  expectedPath: ['verify', 'evaluate'],
  groundTruth: {
    isIncident: false,
    severity: 'P2',
    rootCause: '大促流量上涨触发容量类告警（误报）',
    acceptableCauses: ['大促流量上涨', '容量类告警误报', '流量突增误报'],
    rootCauseKeywords: ['大促', '流量'],
    recovered: true,
  },
  incident: {
    merchant: '麦田会员店',
    severity: 'P2',
    impact: '疑似 ¥12.7万',
    title: '单机房流量倾斜与限流告警',
    detectedAt: '2026-08-26 13:21:56',
  },
  stages: {
    verify: stage({
      stage: 'verify',
      title: '智能核验结果',
      goal: '多源信号聚合判断：流量大涨但核心指标在基线内 + 大促已登记 → 判定误报。',
      context: { incidentId: 'INC-20260825-019', window: '13:17–13:26' },
      tools: [
        {
          name: 'metrics.query',
          displayName: 'Metrics Query',
          category: 'metrics',
          input: { window: '13:17–13:26', granularity: '1m', metrics: ['pay.success_rate', 'merchant.p95_rt', 'pay.qps'] },
          output: {
            successRate: [{ t: '13:17', v: 99.61 }, { t: '13:22', v: 99.52 }, { t: '13:26', v: 99.48 }],
            p95Rt: [{ t: '13:17', v: 128 }, { t: '13:22', v: 134 }, { t: '13:26', v: 141 }],
            qps: [{ t: '13:17', v: 412 }, { t: '13:22', v: 1842 }, { t: '13:26', v: 1690 }],
            throttleRatio: 0.0042,
          },
          latencyMs: 512, status: 'success', flagged: false,
          flagReason: '流量 4.1× 上涨可解释，但成功率偏移 -0.13pp、P95 +13ms 仍在基线内',
          chartHint: 'metric_trend',
        },
        {
          name: 'alerts.context_fetch',
          displayName: 'Alert Context',
          category: 'alert',
          input: { incidentId: 'INC-20260825-019', window: '20m' },
          output: {
            alerts: [{ id: 'ALT-1322', severity: 'P2', rule: 'throttle_ratio>0.3%', firedAt: '13:22:04' }],
            correlatedCount: 1,
            alertCategory: '容量阈值（非错误率）',
            baseline: '大促日 P2 容量告警均值 1.4 条',
          },
          latencyMs: 296, status: 'success', flagged: true,
          flagReason: '容量阈值告警，但同环比下大促日属预期波动',
        },
        {
          name: 'logs.search',
          displayName: 'Logs Search',
          category: 'log',
          input: { service: 'merchant-cashier', keyword: 'error OR fail', window: '13:17–13:26' },
          output: { total: 0, sample: [], topError: null },
          latencyMs: 248, status: 'success', flagged: false,
          flagReason: '未发现错误日志，仅有限流记录',
        },
        {
          name: 'promotion.calendar',
          displayName: 'Promotion Calendar',
          category: 'calendar',
          input: { merchantId: 'm-maitian', date: '2026-08-26' },
          output: { events: [{ id: 'PROMO-0826', name: '麦田会员店 8.26 会员日大促', expectedTrafficMultiplier: '4.0×', registeredAt: '2026-08-20' }] },
          latencyMs: 224, status: 'success', flagged: false,
          flagReason: '大促已提前登记，4.0× 流量预期与观测一致',
        },
      ],
      decision: '流量上涨可被大促日历解释；成功率与延迟均在基线；Logs 无错误；Alerts 仅容量类。综合判定：非故障。',
      decisionFactors: [
        { label: '流量倍率', value: '4.1×', evidence: 'metrics://pay.qps' },
        { label: '成功率偏移', value: '-0.13pp（基线内）', evidence: 'metrics://pay.success_rate' },
        { label: '大促登记', value: '8.26 会员日', evidence: 'calendar://PROMO-0826' },
      ],
      output: {
        isIncident: false,
        severity: 'P2',
        affectedScope: '无实际业务影响',
        falseAlarmReason: '大促流量上涨触发容量阈值告警，成功率与延迟均在基线范围内',
        evidenceGrounded: true,
        signalSummary: '1/4 工具弱 flag（容量类），其余 3 个未 flag',
      },
      metrics: { latencyMs: 1180, inputTokens: 646, outputTokens: 218, costYuan: 0.06, confidence: 94, toolCalls: 4, evidenceCount: 4 },
      gate: '判定非故障需满足：流量可解释 + 成功率与延迟均在基线内 + 日历已登记',
      successMetric: '误报率 ≤ 5%，FN 零容忍',
      risk: '把真实故障误判为流量波动（FN）代价远高于误报。',
      fallback: '任一核心指标越界即按真实故障处理，宁可多走链路。',
    }),
    // ↓ 以下四步仅在真实模型误判为故障（FP）时执行：保证链路不断，同时暴露误判代价。
    locate: stage({
      stage: 'locate',
      title: '根因定位结果',
      goal: '关联指标、日志、变更与历史案例，输出可审计根因。',
      context: { incident: 'P2', service: 'merchant-cashier', window: '13:17–13:26', note: '核验已提示大促流量背景' },
      tools: [
        {
          name: 'metrics.query',
          displayName: 'Metrics Query',
          category: 'metrics',
          input: { window: '13:17–13:26', granularity: '1m', metrics: ['throttle.count', 'cashier.queue'] },
          output: { throttleCount: 142, queueDepth: { avg: 38, peak: 86 }, throttledAtPromoEntry: true },
          latencyMs: 486, status: 'success', flagged: false,
          flagReason: '限流来源集中在营销活动入口，与大促流量同步',
          chartHint: 'metric_trend',
        },
        {
          name: 'logs.search',
          displayName: 'Logs Search',
          category: 'log',
          input: { service: 'merchant-cashier', keyword: 'throttle', window: '13:17–13:26' },
          output: { total: 142, sample: ['13:22:04 INFO throttle entry=cashier-promo-2 ratio=0.42%'] },
          latencyMs: 742, status: 'success', flagged: false,
        },
      ],
      decision: 'Top-1 根因为大促流量触发限流，非系统故障。',
      decisionFactors: [
        { label: '限流来源', value: '营销活动入口', evidence: 'logs://cashier/throttle' },
        { label: '流量相关', value: '与大促峰值同步', evidence: 'metrics://pay.qps' },
      ],
      output: {
        topCause: '大促流量上涨触发限流策略',
        alternatives: ['单机房容量不足'],
        recommendedAction: '临时调高限流阈值并观察，无需故障处置',
        causeOwner: undefined,
      },
      metrics: { latencyMs: 2140, inputTokens: 884, outputTokens: 302, costYuan: 0.09, confidence: 88, toolCalls: 2, evidenceCount: 2 },
      gate: 'Top-1 置信度 ≥ 85%，Evidence Grounding 达标',
      successMetric: 'Root Cause Top-1 Accuracy ≥ 85%',
      risk: '误报进入定位会浪费处置资源。',
      fallback: '定位结论指向非故障时建议回退核验重判。',
    }),
    contact: stage({
      stage: 'contact',
      title: '商户触达方案',
      goal: '生成准确、分级且可操作的商户沟通内容。',
      context: { merchantTier: '重点商户', channel: '站内信', confirmedCause: '大促流量触发限流' },
      tools: [
        {
          name: 'merchant.profile',
          displayName: 'Merchant Profile',
          category: 'merchant',
          input: { merchantId: 'm-maitian', fields: ['tier', 'contacts', 'channel_preference'] },
          output: { tier: '重点商户', channelPreference: ['站内信'] },
          latencyMs: 262, status: 'success', flagged: false,
        },
        {
          name: 'message.composer',
          displayName: 'Message Composer',
          category: 'message',
          input: { facts: ['大促流量 4.1×', '部分请求触发限流', '支付成功率正常'], tone: 'informational' },
          output: { subject: '大促流量限流提醒', message: '监测到您的店铺大促流量达日常 4.1 倍，部分请求触发限流。支付成功率正常，建议关注活动入口容量。', actionLinkLabel: '查看流量详情' },
          latencyMs: 418, status: 'success', flagged: false,
        },
      ],
      decision: '内容已生成，等待人工批准后发送。',
      decisionFactors: [
        { label: '事实边界', value: '仅提示流量与限流状况', evidence: 'trace://locate/output' },
      ],
      output: {
        subject: '大促流量限流提醒',
        message: '监测到您的店铺大促流量达日常 4.1 倍，部分请求触发限流。支付成功率正常，建议关注活动入口容量。',
        actionLinkLabel: '查看流量详情',
      },
      metrics: { latencyMs: 860, inputTokens: 412, outputTokens: 148, costYuan: 0.04, confidence: 92, toolCalls: 2, evidenceCount: 1 },
      gate: '高影响外部动作必须人工批准',
      successMetric: '送达率、点击率与回复率',
      risk: '误报触达会稀释商户对告警的信任。',
      fallback: '拒绝后仅记录内部观察，不打扰商户。',
      requiresApproval: true,
    }),
    escalate: stage({
      stage: 'escalate',
      title: '故障升级结果',
      goal: '依据影响面和持续时间匹配升级策略与责任团队。',
      context: { severity: 'P2', impact: '疑似 ¥12.7万', duration: '10m 12s', recoveryProgress: '指标正常' },
      tools: [
        {
          name: 'policy.engine',
          displayName: 'Policy Engine',
          category: 'policy',
          input: { severity: 'P2', impact: '疑似 ¥12.7万', metricStatus: 'normal' },
          output: { matched: 'P2 + 指标正常 → 不满足升级条件', sla: '无（观察项）' },
          latencyMs: 148, status: 'success', flagged: false,
        },
      ],
      decision: '不满足升级条件，仅记录观察项。',
      decisionFactors: [
        { label: '事故等级', value: 'P2', evidence: 'trace://verify/severity' },
        { label: '指标状态', value: '基线内', evidence: 'metrics://pay.success_rate' },
      ],
      output: { ticketId: 'MOCK-OBS-019', teams: ['商户保障'], sla: '无（观察项）', simulated: true },
      metrics: { latencyMs: 320, inputTokens: 156, outputTokens: 84, costYuan: 0.02, confidence: 97, toolCalls: 1, evidenceCount: 2 },
      gate: 'P0 或影响金额 ≥ ¥100万',
      successMetric: '升级策略命中率与 SLA 达成率',
      risk: '误报升级会放大值班噪声。',
      fallback: '策略不命中时降级为观察项。',
    }),
    recover: stage({
      stage: 'recover',
      title: '恢复判断结果',
      goal: '用连续观测窗口确认真实恢复，防止指标短暂回弹。',
      context: { windows: ['13:30–13:32', '13:32–13:34', '13:34–13:36'], baseline: '近 7 日同小时' },
      tools: [
        {
          name: 'metrics.query',
          displayName: 'Metrics Query',
          category: 'metrics',
          input: { window: '13:30–13:36', granularity: '1m', metrics: ['pay.success_rate', 'pay.qps', 'throttle.ratio'] },
          output: { successRate: [99.55, 99.58, 99.57], qps: [1842, 1818, 1790], throttleRatio: 0.0038 },
          latencyMs: 682, status: 'success', flagged: false,
          flagReason: '三个窗口指标均在基线内，流量平稳回落',
          chartHint: 'metric_trend',
        },
      ],
      decision: '指标持续正常，可以关闭观察。',
      decisionFactors: [
        { label: '支付成功率', value: '99.57%', evidence: 'metrics://pay.success_rate/recovery' },
        { label: '稳定窗口', value: '3/3', evidence: 'metrics://recovery/windows' },
      ],
      output: { recovered: true, stableWindows: 3, residualRisk: '低', observationAdvice: '大促结束前保留流量看板关注' },
      metrics: { latencyMs: 940, inputTokens: 388, outputTokens: 132, costYuan: 0.05, confidence: 96, toolCalls: 1, evidenceCount: 2 },
      gate: '连续三个窗口均回到基线范围',
      successMetric: '恢复误判率与 MTTR',
      risk: '大促期间流量波动可能再次触发告警。',
      fallback: '任一窗口不达标则保持观察打开。',
    }),
    evaluate: stage({
      stage: 'evaluate',
      title: '评测回流结果',
      goal: '把最终处置事实沉淀为可复用评测样本。',
      context: { labelSource: '核验判定 + 营销日历 + 指标基线', promptVersion: 'v3.4', sampleType: '负样本（TN）' },
      tools: [
        {
          name: 'eval.store',
          displayName: 'Eval Store',
          category: 'eval',
          input: { runId: 'RUN-019', tags: ['verify_tn', 'false_alarm', 'promo_calendar'] },
          output: { stored: true, sampleId: 'EVAL-20260826-019' },
          latencyMs: 246, status: 'success', flagged: false,
        },
        {
          name: 'metric.calculator',
          displayName: 'Metric Calculator',
          category: 'metric',
          input: { period: 'today', metrics: ['false_alarm_rate', 'precision'] },
          output: { falseAlarmRate: 0.042, precision: 0.918 },
          latencyMs: 318, status: 'success', flagged: false,
        },
      ],
      decision: '负样本入库：误报收敛能力的评测依据。',
      decisionFactors: [
        { label: '核验结果', value: 'TN', evidence: 'eval://verify/019' },
        { label: '误报归因', value: '大促流量', evidence: 'eval://false-alarm/019' },
        { label: '人工修正', value: '无', evidence: 'eval://human/019' },
      ],
      output: { sampleId: 'EVAL-20260826-019', finalRootCause: '大促流量上涨触发容量类告警（误报）', humanCorrected: false, dataset: 'merchant-incident-v12' },
      metrics: { latencyMs: 588, inputTokens: 296, outputTokens: 118, costYuan: 0.03, confidence: 98, toolCalls: 2, evidenceCount: 3 },
      gate: '最终事实、人工反馈和判定依据齐全',
      successMetric: '误报率、Precision 与告警降噪率',
      risk: '把真实故障标成误报会污染负样本集。',
      fallback: '存疑样本进入人工标注队列。',
    }),
  },
};