import type { RuntimeScenario } from '../types';
import { stage } from './helpers';

// 误报收敛场景：大促流量触发容量类告警，核验判非故障后短路到评测回流（TN 样本）。
// 中间四步仍写全 fixture：真实模式下模型可能误判为故障（FP），链路不能因缺输入而断。
export const falseAlarmScenario: RuntimeScenario = {
  id: 'false-alarm',
  label: '大促误报 P2',
  summary: '大促流量上涨触发限流告警，核验识别为误报并短路回流负样本。',
  incidentId: 'INC-20260825-019',
  monitorImage: '/mock/merchant-monitor-false-alarm.png',
  expectedPath: ['verify', 'evaluate'],
  groundTruth: {
    isIncident: false,
    severity: 'P2',
    rootCause: '大促流量上涨触发容量类告警（误报）',
    acceptableCauses: ['大促流量上涨', '容量类告警误报', '流量突增误报'],
    rootCauseKeywords: ['大促', '流量'],
    recovered: true,
  },
  incident: {
    merchant: '麦田会员店',
    severity: 'P2',
    impact: '疑似 ¥12.7万',
    title: '单机房流量倾斜与限流告警',
    detectedAt: '2026-08-26 13:21:56',
  },
  stages: {
    verify: stage({
      stage: 'verify',
      title: '智能核验结果',
      goal: '确认告警是否为真实故障，并识别影响等级。',
      input: {
        trafficGrowth: '4.1×（大促峰值）',
        paymentSuccessRate: '99.61% → 99.48%',
        p95Latency: '128ms → 141ms',
        throttleRatio: '0.42%',
        promotionCalendar: '已登记：麦田会员店 8.26 会员日大促',
        observationWindow: '连续 5 分钟',
      },
      tools: [
        ['Metrics', '拉取成功率、延迟与流量基线对比', 512],
        ['Promotion Calendar', '检索营销日历确认大促已登记', 224],
        ['Alert Context', '识别告警为容量阈值类而非错误率类', 296],
      ],
      decision: '流量上涨可被大促解释，核心指标在基线内，判定误报。',
      decisionFactors: [
        { label: '流量倍率', value: '4.1×', evidence: 'metric://pay.qps' },
        { label: '成功率偏移', value: '-0.13pp（基线内）', evidence: 'metric://pay.success_rate' },
        { label: '大促登记', value: '8.26 会员日', evidence: 'calendar://promo/0826' },
      ],
      output: {
        isIncident: false,
        severity: 'P2',
        affectedScope: '无实际业务影响',
        falseAlarmReason: '大促流量上涨触发容量阈值告警，成功率与延迟均在基线范围内',
        evidenceGrounded: true,
      },
      metrics: { latencyMs: 1180, inputTokens: 646, outputTokens: 218, costYuan: 0.06, confidence: 94, toolCalls: 3, evidenceCount: 3 },
      gate: '判定非故障需满足：流量可解释 + 成功率与延迟均在基线内',
      successMetric: '误报率 ≤ 5%，FN 零容忍',
      risk: '把真实故障误判为流量波动（FN）代价远高于误报。',
      fallback: '任一核心指标越界即按真实故障处理，宁可多走链路。',
    }),
    // ↓ 以下四步仅在真实模型误判为故障（FP）时执行：保证链路不断，同时暴露误判代价。
    locate: stage({
      stage: 'locate',
      title: '根因定位结果',
      goal: '关联指标、日志、变更与历史案例，输出可审计根因。',
      input: { incident: 'P2', service: 'merchant-cashier', window: '13:17–13:26', note: '核验已提示大促流量背景' },
      tools: [
        ['Metrics', '确认限流触发与流量峰值同步', 486],
        ['Logs', '限流日志集中在营销活动入口', 742],
      ],
      decision: 'Top-1 根因为大促流量触发限流，非系统故障。',
      decisionFactors: [
        { label: '限流来源', value: '营销活动入口', evidence: 'log://cashier/throttle' },
        { label: '流量相关', value: '与大促峰值同步', evidence: 'metric://pay.qps' },
      ],
      output: {
        topCause: '大促流量上涨触发限流策略',
        alternatives: ['单机房容量不足'],
        recommendedAction: '临时调高限流阈值并观察，无需故障处置',
      },
      metrics: { latencyMs: 2140, inputTokens: 884, outputTokens: 302, costYuan: 0.09, confidence: 88, toolCalls: 2, evidenceCount: 2 },
      gate: 'Top-1 置信度 ≥ 85%，Evidence Grounding 达标',
      successMetric: 'Root Cause Top-1 Accuracy ≥ 85%',
      risk: '误报进入定位会浪费处置资源。',
      fallback: '定位结论指向非故障时建议回退核验重判。',
    }),
    contact: stage({
      stage: 'contact',
      title: '商户触达方案',
      goal: '生成准确、分级且可操作的商户沟通内容。',
      input: { merchantTier: '重点商户', channel: '站内信', confirmedCause: '大促流量触发限流' },
      tools: [
        ['Merchant Profile', '读取商户等级与渠道偏好', 262],
        ['Message Composer', '生成流量提醒类通知', 418],
      ],
      decision: '内容已生成，等待人工批准后发送。',
      decisionFactors: [
        { label: '事实边界', value: '仅提示流量与限流状况', evidence: 'trace://locate/output' },
      ],
      output: {
        subject: '大促流量限流提醒',
        message: '监测到您的店铺大促流量达日常 4.1 倍，部分请求触发限流。支付成功率正常，建议关注活动入口容量。',
        actionLink: '查看流量详情',
      },
      metrics: { latencyMs: 860, inputTokens: 412, outputTokens: 148, costYuan: 0.04, confidence: 92, toolCalls: 2, evidenceCount: 1 },
      gate: '高影响外部动作必须人工批准',
      successMetric: '送达率、点击率与回复率',
      risk: '误报触达会稀释商户对告警的信任。',
      fallback: '拒绝后仅记录内部观察，不打扰商户。',
      requiresApproval: true,
    }),
    escalate: stage({
      stage: 'escalate',
      title: '故障升级结果',
      goal: '依据影响面和持续时间匹配升级策略与责任团队。',
      input: { severity: 'P2', impact: '疑似 ¥12.7万', duration: '10m 12s', recoveryProgress: '指标正常' },
      tools: [
        ['Policy Engine', 'P2 且指标正常：不满足升级条件', 148],
      ],
      decision: '不满足升级条件，仅记录观察项。',
      decisionFactors: [
        { label: '事故等级', value: 'P2', evidence: 'trace://verify/severity' },
        { label: '指标状态', value: '基线内', evidence: 'metric://pay.success_rate' },
      ],
      output: { ticketId: 'MOCK-OBS-019', teams: ['商户保障'], sla: '无（观察项）', simulated: true },
      metrics: { latencyMs: 320, inputTokens: 156, outputTokens: 84, costYuan: 0.02, confidence: 97, toolCalls: 1, evidenceCount: 2 },
      gate: 'P0 或影响金额 ≥ ¥100万',
      successMetric: '升级策略命中率与 SLA 达成率',
      risk: '误报升级会放大值班噪声。',
      fallback: '策略不命中时降级为观察项。',
    }),
    recover: stage({
      stage: 'recover',
      title: '恢复判断结果',
      goal: '用连续观测窗口确认真实恢复，防止指标短暂回弹。',
      input: { windows: ['13:30–13:32', '13:32–13:34', '13:34–13:36'], baseline: '近 7 日同小时' },
      tools: [
        ['Metrics', '确认三个窗口指标均在基线内', 682],
      ],
      decision: '指标持续正常，可以关闭观察。',
      decisionFactors: [
        { label: '支付成功率', value: '99.57%', evidence: 'metric://pay.success_rate/recovery' },
        { label: '稳定窗口', value: '3/3', evidence: 'metric://recovery/windows' },
      ],
      output: { recovered: true, stableWindows: 3, residualRisk: '低', observationAdvice: '大促结束前保留流量看板关注' },
      metrics: { latencyMs: 940, inputTokens: 388, outputTokens: 132, costYuan: 0.05, confidence: 96, toolCalls: 1, evidenceCount: 2 },
      gate: '连续三个窗口均回到基线范围',
      successMetric: '恢复误判率与 MTTR',
      risk: '大促期间流量波动可能再次触发告警。',
      fallback: '任一窗口不达标则保持观察打开。',
    }),
    evaluate: stage({
      stage: 'evaluate',
      title: '评测回流结果',
      goal: '把最终处置事实沉淀为可复用评测样本。',
      input: { labelSource: '核验判定 + 营销日历 + 指标基线', promptVersion: 'v3.4', sampleType: '负样本（TN）' },
      tools: [
        ['Eval Store', '写入误报判定与归因标签', 246],
        ['Metric Calculator', '刷新误报率与 Precision 指标', 318],
      ],
      decision: '负样本入库：误报收敛能力的评测依据。',
      decisionFactors: [
        { label: '核验结果', value: 'TN', evidence: 'eval://verify/019' },
        { label: '误报归因', value: '大促流量', evidence: 'eval://false-alarm/019' },
        { label: '人工修正', value: '无', evidence: 'eval://human/019' },
      ],
      output: { sampleId: 'EVAL-20260826-019', finalRootCause: '大促流量上涨触发容量类告警（误报）', humanCorrected: false, dataset: 'merchant-incident-v12' },
      metrics: { latencyMs: 588, inputTokens: 296, outputTokens: 118, costYuan: 0.03, confidence: 98, toolCalls: 2, evidenceCount: 3 },
      gate: '最终事实、人工反馈和判定依据齐全',
      successMetric: '误报率、Precision 与告警降噪率',
      risk: '把真实故障标成误报会污染负样本集。',
      fallback: '存疑样本进入人工标注队列。',
    }),
  },
};
