import type { RuntimeScenario } from '../types';
import { stage } from './helpers';

// 黄金场景：数据跌落型 P0，走完整六步线性路径（含人工审批）。
// 多源信号聚合：verify 阶段同时调用 Metrics / Alerts / Logs / Change Records，4 源一致指向真实故障。
export const gatewayTimeoutScenario: RuntimeScenario = {
  id: 'gateway-timeout',
  label: '网关超时 P0',
  summary: '支付成功率断崖下跌，全链路六步线性处置的黄金路径。',
  incidentId: 'INC-20260825-031',
  expectedPath: ['verify', 'locate', 'contact', 'escalate', 'recover', 'evaluate'],
  groundTruth: {
    isIncident: true,
    severity: 'P0',
    rootCause: '商户 API 网关连接池耗尽',
    acceptableCauses: ['连接池耗尽', '网关连接池配置错误'],
    rootCauseKeywords: ['连接池'],
    recovered: true,
  },
  incident: {
    merchant: '星海出行',
    severity: 'P0',
    impact: '¥286.4万',
    title: '支付接口超时率突增',
    detectedAt: '2026-08-26 14:23:18',
  },
  stages: {
    verify: stage({
      stage: 'verify',
      title: '智能核验结果',
      goal: '多源信号聚合判断：4 类内部接口工具共同核验异常，避免单一指标下结论。',
      context: { incidentId: 'INC-20260825-031', window: '14:18–14:27' },
      tools: [
        {
          name: 'metrics.query',
          displayName: 'Metrics Query',
          category: 'metrics',
          input: { window: '14:18–14:27', granularity: '1m', metrics: ['pay.success_rate', 'merchant.p95_rt', 'pay.qps'] },
          output: {
            successRate: [{ t: '14:18', v: 99.72 }, { t: '14:23', v: 71.36 }, { t: '14:27', v: 74.18 }],
            p95Rt: [{ t: '14:18', v: 126 }, { t: '14:23', v: 4620 }, { t: '14:27', v: 4380 }],
            qps: [{ t: '14:18', v: 1842 }, { t: '14:23', v: 1798 }, { t: '14:27', v: 1812 }],
          },
          latencyMs: 486, status: 'success', flagged: true,
          flagReason: '成功率跌破基线 -28.36pp，P95 升至 36.7×',
          chartHint: 'metric_trend',
        },
        {
          name: 'alerts.context_fetch',
          displayName: 'Alert Context',
          category: 'alert',
          input: { incidentId: 'INC-20260825-031', window: '20m' },
          output: {
            alerts: [
              { id: 'ALT-1418', severity: 'P0', rule: 'success_rate<95%', firedAt: '14:18:32' },
              { id: 'ALT-1419', severity: 'P0', rule: 'p95_rt>3000ms', firedAt: '14:19:04' },
              { id: 'ALT-1421', severity: 'P0', rule: 'error_rate>5%', firedAt: '14:21:18' },
            ],
            correlatedCount: 3,
            baseline: '近 7 日同小时 P0 告警 0.2 条/小时',
          },
          latencyMs: 318, status: 'success', flagged: true,
          flagReason: '20 分钟内触发 3 条 P0 告警，远超基线',
        },
        {
          name: 'logs.search',
          displayName: 'Logs Search',
          category: 'log',
          input: { service: 'merchant-api-gateway', errorCode: '504', window: '14:18–14:27' },
          output: {
            total: 18432,
            sample: [
              '14:23:14 ERROR pool acquire timeout (gateway-pool-12, queue=248)',
              '14:23:18 ERROR pool acquire timeout (gateway-pool-12, queue=312)',
              '14:23:21 ERROR upstream gateway timeout (id=gw-9821, code=504)',
            ],
            topError: 'pool acquire timeout',
          },
          latencyMs: 920, status: 'success', flagged: true,
          flagReason: '504 + pool acquire timeout 集中爆发，时间窗与指标吻合',
          chartHint: 'log_excerpt',
        },
        {
          name: 'change_records.list',
          displayName: 'Change Records',
          category: 'change',
          input: { services: ['merchant-api-gateway'], window: '24h' },
          output: {
            changes: [
              { id: 'CHG-0826-1419', type: 'config', summary: '连接池 max_per_route 由 200 → 400', at: '14:19:02', author: 'gateway-team' },
              { id: 'CHG-0826-1015', type: 'deploy', summary: 'merchant-api-gateway v3.4.2 灰度 30%', at: '10:15:00', author: 'sre-bot' },
            ],
            note: '14:19 配置变更与告警起点高度对齐',
          },
          latencyMs: 248, status: 'success', flagged: true,
          flagReason: '变更时间窗与告警起点对齐，可能为诱因',
          chartHint: 'change_timeline',
        },
      ],
      decision: '4 源工具均检出异常：Metrics 跌破基线、Alerts 远超基线、Logs 集中爆发、Change Records 时间对齐 → 真实 P0 故障。',
      decisionFactors: [
        { label: '成功率跌幅', value: '-28.36pp', evidence: 'metrics://pay.success_rate' },
        { label: 'P95 倍率', value: '36.7×', evidence: 'metrics://merchant.p95_rt' },
        { label: '变更时间窗', value: '告警起点 14:19', evidence: 'change://CHG-0826-1419' },
      ],
      output: {
        isIncident: true,
        severity: 'P0',
        affectedScope: '星海出行支付接口',
        evidenceGrounded: true,
        signalSummary: '4/4 工具异常聚合',
      },
      metrics: { latencyMs: 1240, inputTokens: 612, outputTokens: 230, costYuan: 0.06, confidence: 96, toolCalls: 4, evidenceCount: 4 },
      gate: '真实故障且置信度 ≥ 90%',
      successMetric: 'P0 Recall ≥ 99%',
      risk: '单源信号可能造成误报；多源对齐才能闭环。',
      fallback: '多源不一致时转人工核验，不自动升级。',
    }),
    locate: stage({
      stage: 'locate',
      title: '根因定位结果',
      goal: '关联指标、日志、变更与历史案例，输出可审计根因。',
      context: { incident: 'P0', service: 'merchant-api-gateway', window: '14:18–14:27' },
      tools: [
        {
          name: 'logs.search',
          displayName: 'Logs Search（深查）',
          category: 'log',
          input: { service: 'merchant-api-gateway', keyword: 'pool acquire timeout', window: '14:18–14:27' },
          output: {
            total: 18432,
            pattern: 'pool acquire timeout',
            sample: [
              '14:23:14 pool acquire timeout (gateway-pool-12, queue=248/400)',
              '14:23:18 pool acquire timeout (gateway-pool-12, queue=312/400)',
              '14:23:21 pool acquire timeout (gateway-pool-12, queue=387/400)',
            ],
          },
          latencyMs: 1320, status: 'success', flagged: true,
          flagReason: '连接池队列深度持续贴近上限 400/400',
          chartHint: 'log_excerpt',
        },
        {
          name: 'change_records.list',
          displayName: 'Change Records（深查）',
          category: 'change',
          input: { services: ['merchant-api-gateway'], window: '4h' },
          output: {
            changes: [
              { id: 'CHG-0826-1419', type: 'config', summary: '连接池 max_per_route 由 200 → 400', at: '14:19:02', author: 'gateway-team', related: true },
              { id: 'CHG-0826-1015', type: 'deploy', summary: 'merchant-api-gateway v3.4.2 灰度 30%', at: '10:15:00', author: 'sre-bot', related: false },
            ],
          },
          latencyMs: 584, status: 'success', flagged: true,
          flagReason: '14:19 连接池参数变更直接相关（变更前 4 分钟告警）',
          chartHint: 'change_timeline',
        },
        {
          name: 'case_rag.retrieve',
          displayName: 'Case RAG',
          category: 'case',
          input: { query: '网关连接池耗尽 504 集中爆发', topK: 3 },
          output: {
            cases: [
              { id: 'CASE-20260718-044', title: '连接池耗尽导致网关超时', similarity: 0.914, resolved: '回滚参数并扩容' },
              { id: 'CASE-20260522-007', title: '下游网络抖动误判为连接池', similarity: 0.732, resolved: '实际是网络抖动' },
            ],
          },
          latencyMs: 1486, status: 'success', flagged: true,
          flagReason: '召回 2026-07-18 同型案例，相似度 91.4%',
          chartHint: 'case_similarity',
        },
      ],
      decision: 'Top-1 根因为商户 API 网关连接池耗尽（参数变更后队列触顶）。',
      decisionFactors: [
        { label: '日志命中', value: '18,432 条', evidence: 'logs://gateway/pool-timeout' },
        { label: '变更相关', value: '告警前 4 分钟', evidence: 'change://CHG-0826-1419' },
        { label: '案例相似度', value: '91.4%', evidence: 'case://2026-07-18-044' },
      ],
      output: {
        topCause: '商户 API 网关连接池耗尽',
        alternatives: ['下游网络抖动', '单机房流量倾斜'],
        recommendedAction: '回滚连接池参数并扩容实例',
        causeOwner: undefined,
      },
      metrics: { latencyMs: 4380, inputTokens: 1482, outputTokens: 482, costYuan: 0.18, confidence: 93, toolCalls: 3, evidenceCount: 3 },
      gate: 'Top-1 置信度 ≥ 85%，Evidence Grounding 达标',
      successMetric: 'Root Cause Top-1 Accuracy ≥ 85%',
      risk: '历史案例相似不代表根因必然相同。',
      fallback: '展示 Top-3 和反证，交由值班工程师确认。',
    }),
    contact: stage({
      stage: 'contact',
      title: '商户触达方案',
      goal: '基于 Merchant Profile 生成准确、分级且可操作的商户沟通内容。',
      context: { merchantTier: '战略商户', channel: '站内信 + 短信', confirmedCause: '连接池耗尽' },
      tools: [
        {
          name: 'merchant.profile',
          displayName: 'Merchant Profile',
          category: 'merchant',
          input: { merchantId: 'm-xinghai', fields: ['tier', 'contacts', 'channel_preference', 'tech_capability'] },
          output: {
            tier: '战略商户',
            contacts: [{ name: '李工', role: '技术负责人', phone: '+86-138****2102' }],
            channelPreference: ['站内信', '短信'],
            techCapability: '有 SRE 团队，可在 15 分钟内自查',
        },
          latencyMs: 286, status: 'success', flagged: false,
          flagReason: '画像正常',
        },
        {
          name: 'message.composer',
          displayName: 'Message Composer',
          category: 'message',
          input: { facts: ['14:19 连接池参数变更后支付接口成功率跌至 71%', '已临时扩容并准备回滚'], tone: 'incident_brief', channel: ['站内信', '短信'] },
          output: {
            subject: '支付接口异常处置通知',
            message: '检测到支付接口连接池耗尽。建议回滚 14:19 参数变更并扩容实例，我们将持续同步恢复进展。',
            actionLinkLabel: '查看排查步骤',
          },
          latencyMs: 504, status: 'success', flagged: false,
          flagReason: '内容仅引用已确认事实',
        },
      ],
      decision: '触达内容已生成，等待人工批准后发送。',
      decisionFactors: [
        { label: '事实边界', value: '仅引用已确认根因', evidence: 'trace://locate/output' },
        { label: '触达策略', value: '站内信 + 短信', evidence: 'merchant://profile/channel' },
      ],
      output: {
        subject: '支付接口异常处置通知',
        message: '检测到支付接口连接池耗尽。建议回滚 14:19 参数变更并扩容实例，我们将持续同步恢复进展。',
        actionLinkLabel: '查看排查步骤',
      },
      metrics: { latencyMs: 980, inputTokens: 448, outputTokens: 164, costYuan: 0.05, confidence: 95, toolCalls: 2, evidenceCount: 2 },
      gate: '高影响外部动作必须人工批准',
      successMetric: '送达率、点击率与回复率',
      risk: '未经确认的信息可能造成商户误解。',
      fallback: '拒绝后转人工电话沟通并记录原因。',
      requiresApproval: true,
    }),
    escalate: stage({
      stage: 'escalate',
      title: '故障升级结果',
      goal: '依据影响面和持续时间匹配升级策略与责任团队。',
      context: { severity: 'P0', impact: '¥286.4万', duration: '11m 06s', recoveryProgress: '未恢复' },
      tools: [
        {
          name: 'policy.engine',
          displayName: 'Policy Engine',
          category: 'policy',
          input: { severity: 'P0', impact: '¥286.4万', merchantTier: '战略商户' },
          output: { matched: 'P0 战略商户双团队联合升级', sla: '15 分钟' },
          latencyMs: 164, status: 'success', flagged: false,
          flagReason: '策略命中',
        },
        {
          name: 'oncall.directory',
          displayName: 'On-call Directory',
          category: 'oncall',
          input: { teams: ['merchant-assurance', 'gateway-platform'] },
          output: { oncall: [{ team: '商户保障', primary: '王*', secondary: '陈*' }, { team: '网关平台', primary: '刘*', secondary: '赵*' }] },
          latencyMs: 142, status: 'success', flagged: false,
        },
        {
          name: 'ticket.create',
          displayName: 'Ticket',
          category: 'ticket',
          input: { severity: 'P0', title: 'MOCK-INC-031 网关连接池耗尽', teams: ['商户保障', '网关平台'] },
          output: { ticketId: 'MOCK-INC-031', simulated: true },
          latencyMs: 154, status: 'success', flagged: false,
        },
      ],
      decision: '升级至双团队联合处置，SLA 15 分钟。',
      decisionFactors: [
        { label: '事故等级', value: 'P0', evidence: 'trace://verify/severity' },
        { label: '影响金额', value: '¥286.4万', evidence: 'impact://estimate/031' },
      ],
      output: { ticketId: 'MOCK-INC-031', teams: ['商户保障', '网关平台'], sla: '15 分钟', simulated: true },
      metrics: { latencyMs: 460, inputTokens: 184, outputTokens: 102, costYuan: 0.03, confidence: 98, toolCalls: 3, evidenceCount: 2 },
      gate: 'P0 或影响金额 ≥ ¥100万',
      successMetric: '升级策略命中率与 SLA 达成率',
      risk: '过度升级会增加值班噪声。',
      fallback: '策略冲突时选择更高等级并提示人工确认。',
    }),
    recover: stage({
      stage: 'recover',
      title: '恢复判断结果',
      goal: '用连续观测窗口确认真实恢复，防止指标短暂回弹。',
      context: { windows: ['14:37–14:39', '14:39–14:41', '14:41–14:43'], baseline: '近 7 日同小时' },
      tools: [
        {
          name: 'metrics.query',
          displayName: 'Metrics Query',
          category: 'metrics',
          input: { window: '14:37–14:43', granularity: '1m', metrics: ['pay.success_rate', 'merchant.p95_rt'] },
          output: {
            successRate: [{ t: '14:37', v: 99.62 }, { t: '14:39', v: 99.68 }, { t: '14:41', v: 99.71 }, { t: '14:43', v: 99.66 }],
            p95Rt: [{ t: '14:37', v: 142 }, { t: '14:39', v: 139 }, { t: '14:41', v: 136 }, { t: '14:43', v: 144 }],
          },
          latencyMs: 1040, status: 'success', flagged: false,
          flagReason: '三个窗口成功率 99.6%+，P95 回到 140ms 左右',
          chartHint: 'metric_trend',
        },
        {
          name: 'logs.search',
          displayName: 'Logs Search',
          category: 'log',
          input: { service: 'merchant-api-gateway', keyword: 'pool acquire timeout', window: '14:37–14:43' },
          output: { total: 6, sample: ['14:38 警告级别（队列深度 <50%）'], topError: null },
          latencyMs: 486, status: 'success', flagged: false,
          flagReason: 'pool timeout 已降至正常范围',
        },
      ],
      decision: '连续三个窗口稳定，事故可以关闭。',
      decisionFactors: [
        { label: '支付成功率', value: '99.68%', evidence: 'metrics://pay.success_rate/recovery' },
        { label: 'P95 RT', value: '139ms', evidence: 'metrics://merchant.p95_rt/recovery' },
        { label: '稳定窗口', value: '3/3', evidence: 'metrics://recovery/windows' },
      ],
      output: { recovered: true, stableWindows: 3, residualRisk: '低', observationAdvice: '继续观察 15 分钟' },
      metrics: { latencyMs: 1860, inputTokens: 542, outputTokens: 192, costYuan: 0.1, confidence: 94, toolCalls: 2, evidenceCount: 3 },
      gate: '连续三个窗口均回到基线范围',
      successMetric: '恢复误判率与 MTTR',
      risk: '单窗口恢复可能只是短暂回弹。',
      fallback: '任一窗口不达标则保持事故打开。',
    }),
    evaluate: stage({
      stage: 'evaluate',
      title: '评测回流结果',
      goal: '把最终处置事实沉淀为可复用评测样本。',
      context: { labelSource: '最终工单 + 人工审批 + 恢复窗口', promptVersion: 'v3.4' },
      tools: [
        {
          name: 'eval.store',
          displayName: 'Eval Store',
          category: 'eval',
          input: { runId: 'RUN-031', tags: ['verify_tp', 'root_cause_top1', 'no_human_correction'] },
          output: { stored: true, sampleId: 'EVAL-20260826-031' },
          latencyMs: 284, status: 'success', flagged: false,
        },
        {
          name: 'metric.calculator',
          displayName: 'Metric Calculator',
          category: 'metric',
          input: { period: 'today', metrics: ['recall', 'precision', 'top1_accuracy'] },
          output: { recall: 0.987, precision: 0.914, top1Accuracy: 0.869 },
          latencyMs: 362, status: 'success', flagged: false,
        },
      ],
      decision: '样本通过质量检查并进入常态化评测集。',
      decisionFactors: [
        { label: '核验结果', value: 'TP', evidence: 'eval://verify/031' },
        { label: 'Top-1 根因', value: '命中', evidence: 'eval://root-cause/031' },
        { label: '人工修正', value: '无', evidence: 'eval://human/031' },
      ],
      output: { sampleId: 'EVAL-20260826-031', finalRootCause: '商户 API 网关连接池耗尽', humanCorrected: false, dataset: 'merchant-incident-v12' },
      metrics: { latencyMs: 646, inputTokens: 324, outputTokens: 126, costYuan: 0.04, confidence: 99, toolCalls: 2, evidenceCount: 3 },
      gate: '最终事实、人工反馈和恢复结果齐全',
      successMetric: 'Recall、F1、Top-K、Grounding 与人工接管率',
      risk: '错误标签会放大后续评测偏差。',
      fallback: '证据不完整的样本进入待标注队列。',
    }),
  },
};