import type { RuntimeScenario } from '../types';
import { stage } from './helpers';

// 商户侧根因场景：故障根源在商户自身（证书过期），触达从「通知」变「指导修复」，
// 升级降为低级别通报——根因归属（causeOwner）决定处置策略是本场景的产品抓手。
export const merchantCertScenario: RuntimeScenario = {
  id: 'merchant-cert',
  label: '商户证书 P1',
  summary: '商户支付证书过期导致签名失败，AI 指导商户自助修复而非内部升级。',
  incidentId: 'INC-20260825-028',
  monitorImage: '/mock/merchant-monitor-merchant-cert.png',
  expectedPath: ['verify', 'locate', 'contact', 'escalate', 'recover', 'evaluate'],
  groundTruth: {
    isIncident: true,
    severity: 'P1',
    rootCause: '商户支付公钥证书已过期',
    acceptableCauses: ['证书过期', '商户证书失效'],
    rootCauseKeywords: ['证书', '过期'],
    recovered: true,
  },
  incident: {
    merchant: '云杉生活',
    severity: 'P1',
    impact: '¥64.8万',
    title: '签名校验失败持续升高',
    detectedAt: '2026-08-26 14:08:42',
  },
  stages: {
    verify: stage({
      stage: 'verify',
      title: '智能核验结果',
      goal: '确认告警是否为真实故障，并识别影响等级。',
      input: {
        paymentSuccessRate: '99.68% → 88.21%',
        signFailureGrowth: '61.2×',
        errorCode: 'SIGN_VERIFY_FAILED 占失败请求 96.4%',
        p95Latency: '132ms → 138ms（正常）',
        observationWindow: '连续 6 分钟',
      },
      tools: [
        ['Metrics', '成功率下跌但延迟与流量均正常', 462],
        ['Error Analyzer', '失败集中于单一错误码 SIGN_VERIFY_FAILED', 388],
      ],
      decision: '真实 P1 故障：错误码单一、延迟正常，指向配置/凭证类问题。',
      decisionFactors: [
        { label: '成功率跌幅', value: '-11.47pp', evidence: 'metric://pay.success_rate' },
        { label: '错误码集中度', value: '96.4%', evidence: 'error://sign-verify-failed' },
        { label: '延迟状态', value: '正常（排除容量问题）', evidence: 'metric://merchant.p95_rt' },
      ],
      output: {
        isIncident: true,
        severity: 'P1',
        affectedScope: '云杉生活签名校验链路',
        evidenceGrounded: true,
      },
      metrics: { latencyMs: 1150, inputTokens: 598, outputTokens: 212, costYuan: 0.06, confidence: 95, toolCalls: 2, evidenceCount: 3 },
      gate: '真实故障且置信度 ≥ 90%',
      successMetric: 'P1 Recall ≥ 97%',
      risk: '错误码集中也可能是平台侧验签服务异常。',
      fallback: '置信度不足时转人工核验，不自动升级。',
    }),
    locate: stage({
      stage: 'locate',
      title: '根因定位结果',
      goal: '关联指标、日志、变更与历史案例，输出可审计根因并判定归属。',
      input: { incident: 'P1', service: 'open-api-signature', window: '14:02–14:12', errorCode: 'SIGN_VERIFY_FAILED' },
      tools: [
        ['Cert Inspector', '商户公钥证书 14:05 过期', 524],
        ['Logs', 'cert expired 拒绝记录 9,216 条', 918],
        ['Change Records', '平台侧验签服务无变更', 342],
        ['Case RAG', '召回 3 起证书过期同型案例', 1268],
      ],
      decision: 'Top-1 根因为商户支付公钥证书过期，归属商户侧。',
      decisionFactors: [
        { label: '证书状态', value: '14:05 已过期', evidence: 'cert://merchant/yunshan/expiry' },
        { label: '平台侧变更', value: '无', evidence: 'change://open-api/none' },
        { label: '案例相似度', value: '95.2%', evidence: 'case://2026-06-30-017' },
      ],
      output: {
        topCause: '商户支付公钥证书已过期',
        alternatives: ['商户签名算法配置变更', '平台验签服务异常'],
        causeOwner: 'merchant',
        recommendedAction: '指导商户更新证书并重新上传公钥',
      },
      metrics: { latencyMs: 3620, inputTokens: 1324, outputTokens: 436, costYuan: 0.15, confidence: 94, toolCalls: 4, evidenceCount: 4 },
      gate: 'Top-1 置信度 ≥ 85%，根因归属明确',
      successMetric: 'Root Cause Top-1 Accuracy ≥ 85%，归属判定准确率',
      risk: '归属判错会把商户问题升级给平台团队，浪费值班资源。',
      fallback: '归属存疑时按平台侧处理（宁可多查，不漏平台故障）。',
    }),
    contact: stage({
      stage: 'contact',
      title: '商户触达方案',
      goal: '根因在商户侧：生成分步修复指导，而不是单向故障通知。',
      input: { merchantTier: '重点商户', channel: '站内信 + 商户热线外呼', confirmedCause: '商户证书过期', techLevel: '有专职技术团队' },
      tools: [
        ['Merchant Profile', '商户有技术团队，可自助完成证书更新', 274],
        ['Message Composer', '生成分步修复指导与自查清单', 536],
      ],
      decision: '修复指导已生成，等待人工批准后发送。',
      decisionFactors: [
        { label: '触达类型', value: '指导修复（根因在商户侧）', evidence: 'trace://locate/causeOwner' },
        { label: '技术能力', value: '有专职技术团队', evidence: 'merchant://profile/tech' },
      ],
      output: {
        subject: '您的支付证书已过期，请尽快更新',
        message: '检测到贵司支付公钥证书于 14:05 过期，导致签名校验失败、支付成功率下降。请按以下步骤更新证书，更新后 5 分钟内生效。',
        guidanceSteps: ['登录开放平台控制台，进入「密钥/证书管理」', '重新生成或上传有效期内的公钥证书', '用沙箱环境验签通过后切回生产'],
        actionLinkLabel: '打开证书管理控制台',
      },
      metrics: { latencyMs: 1040, inputTokens: 486, outputTokens: 196, costYuan: 0.05, confidence: 96, toolCalls: 2, evidenceCount: 2 },
      gate: '高影响外部动作必须人工批准',
      successMetric: '商户自助修复完成率、修复时长',
      risk: '指导步骤有误会延长商户故障时间。',
      fallback: '商户 15 分钟未响应则升级为电话+技术支持介入。',
      requiresApproval: true,
    }),
    escalate: stage({
      stage: 'escalate',
      title: '故障升级结果',
      goal: '根因在商户侧：低级别通报商户技术支持跟进，不拉平台值班。',
      input: { severity: 'P1', impact: '¥64.8万', duration: '18m 20s', causeOwner: 'merchant', recoveryProgress: '待商户修复' },
      tools: [
        ['Policy Engine', '命中「商户侧根因」低级别通报策略', 156],
        ['Ticket', '创建跟进单 MOCK-INC-028（商户技术支持）', 148],
      ],
      decision: '低级别通报：商户技术支持跟进修复进度，平台侧仅观察。',
      decisionFactors: [
        { label: '根因归属', value: '商户侧', evidence: 'trace://locate/causeOwner' },
        { label: '升级策略', value: '不拉平台值班', evidence: 'policy://merchant-owned-cause' },
      ],
      output: { ticketId: 'MOCK-INC-028', teams: ['商户技术支持'], sla: '30 分钟跟进', escalationLevel: '低级别通报', simulated: true },
      metrics: { latencyMs: 380, inputTokens: 172, outputTokens: 96, costYuan: 0.02, confidence: 97, toolCalls: 2, evidenceCount: 2 },
      gate: '根因归属商户侧且商户具备修复能力',
      successMetric: '升级策略命中率、平台值班噪声下降',
      risk: '归属误判会导致平台故障漏升级。',
      fallback: '商户修复超时或指标继续恶化则升级平台值班。',
    }),
    recover: stage({
      stage: 'recover',
      title: '恢复判断结果',
      goal: '用连续观测窗口确认真实恢复，防止指标短暂回弹。',
      input: { windows: ['14:31–14:33', '14:33–14:35', '14:35–14:37'], baseline: '近 7 日同小时', merchantAction: '商户 14:28 已更新证书' },
      tools: [
        ['Metrics', '三个窗口成功率均回到基线', 892],
        ['Cert Inspector', '新证书有效期至 2027-08', 236],
      ],
      decision: '证书已更新且连续三个窗口稳定，事故可以关闭。',
      decisionFactors: [
        { label: '支付成功率', value: '99.65%', evidence: 'metric://pay.success_rate/recovery' },
        { label: '证书状态', value: '有效（2027-08 到期）', evidence: 'cert://merchant/yunshan/renewed' },
        { label: '稳定窗口', value: '3/3', evidence: 'metric://recovery/windows' },
      ],
      output: { recovered: true, stableWindows: 3, residualRisk: '低', observationAdvice: '建议商户配置证书到期前 30 天提醒' },
      metrics: { latencyMs: 1420, inputTokens: 512, outputTokens: 178, costYuan: 0.08, confidence: 96, toolCalls: 2, evidenceCount: 3 },
      gate: '连续三个窗口均回到基线范围',
      successMetric: '恢复误判率与 MTTR',
      risk: '证书更新未全量生效时可能残留失败。',
      fallback: '任一窗口不达标则保持事故打开。',
    }),
    evaluate: stage({
      stage: 'evaluate',
      title: '评测回流结果',
      goal: '把最终处置事实沉淀为可复用评测样本。',
      input: { labelSource: '证书检查 + 商户修复回执 + 恢复窗口', promptVersion: 'v3.4' },
      tools: [
        ['Eval Store', '写入根因归属与触达策略标签', 268],
        ['Metric Calculator', '刷新归属判定与自助修复率指标', 344],
      ],
      decision: '样本通过质量检查，商户侧根因案例入库。',
      decisionFactors: [
        { label: '核验结果', value: 'TP', evidence: 'eval://verify/028' },
        { label: 'Top-1 根因', value: '命中', evidence: 'eval://root-cause/028' },
        { label: '归属判定', value: '商户侧（正确）', evidence: 'eval://cause-owner/028' },
      ],
      output: { sampleId: 'EVAL-20260826-028', finalRootCause: '商户支付公钥证书已过期', humanCorrected: false, dataset: 'merchant-incident-v12' },
      metrics: { latencyMs: 612, inputTokens: 308, outputTokens: 122, costYuan: 0.04, confidence: 98, toolCalls: 2, evidenceCount: 3 },
      gate: '最终事实、人工反馈和恢复结果齐全',
      successMetric: 'Recall、F1、归属准确率与自助修复率',
      risk: '错误标签会放大后续评测偏差。',
      fallback: '证据不完整的样本进入待标注队列。',
    }),
  },
};
